### ISSUE TITLE
Testing Round 1

### ISSUE THREAD

**Issue by IronRunes** [the-engine-room/research-findings#10]

**Comment by thomwithoutanh** [comment]
generally, it's lovely! :)

- [x] Increase space between horizontal line and text on 'prove it', 'so what' and 'see all content' text 
![image](https://user-images.githubusercontent.com/9477277/31776540-bdca3be2-b4e3-11e7-8a5b-d788c9835d18.png)

- [x] Fix issue when messages are expanded they expand into the footer. This also happens with 'show all content'
![image](https://user-images.githubusercontent.com/9477277/31776699-27717ff6-b4e4-11e7-9db3-646e52165055.png)

- [x] When you expand all 'prove it' and 'so what' boxes, it works up until message 4, when it's not possible to expand the text there or in message 5. 

- [x] Resize Engine Room and MAVC logos so that they are aligned
![image](https://user-images.githubusercontent.com/9477277/31776774-51cfa606-b4e4-11e7-964d-12a5aafda8d8.png)

- [x] Increase size of funder logos and ensure that they are of a similar size
![image](https://user-images.githubusercontent.com/9477277/31776871-9aa043b8-b4e4-11e7-88a3-943267e6dd40.png)

- [x] Add creative commons logo in the footer (now added in the logos folder)

- [x] Fix issue where text expands into footer when you click 'see all content':

![image](https://user-images.githubusercontent.com/9477277/31777264-9105ecd0-b4e5-11e7-9b1e-beea0a03f9a1.png)

- [x] Fix display on mobile where sections are displaying on top of each other.  
![image](https://user-images.githubusercontent.com/9477277/31778849-966e54ec-b4e9-11e7-9d26-693a6e199173.png)

- [x] To highlight that "Prove it" and "So what" are clickable, it'd be great if the :hover colour could be #007FFF

- [x] Could we lower the lines under "Prove it" and "OK, so what" a little bit (maybe 2 or 3px) - they're a bit too close: 
![image](https://user-images.githubusercontent.com/20791438/31818552-f2b0f2d2-b598-11e7-9b29-2e8d54dd9e40.png)


- [x] Low-priority: is there any more visual thing that we can add to the 'read the research' link? An icon like this perhaps? https://thenounproject.com/search/?q=document&i=1212327 Although if it wouldn't work, feel free to let me know.

- [ ] Low priority thought: a part of me wanted to contract the 'prove it' and 'so what' boxes after reading them. Not 100% sure it's needed, but if it's easy to do, worth a go?

* * * 
**Things that Paola and I can do easily**



- [x] remove line breaks between text and 'read full research' 
![image](https://user-images.githubusercontent.com/9477277/31776648-04bbe49c-b4e4-11e7-884b-142dfda3fde9.png)

- [x] Create tweet-links for all 5 messages and 'tweet this site'

- [x] Correct typo in footer - from 'Making All Voice Count is implemented by' to 'Making All Voices Count is...'

- [x] Correct typo in footer - from 'Making All Voice Count is funded by' to 'Making All Voices Count is...'

- [x] In footer, change link from 'http://www.makingallvoicescount.org' to  'http://www.makingallvoicescount.org/publication/ and link text to 'read all Making All Voices Count's research'

- [x] Bold first line of 'prove it'

- [x] Add alt text to all 'Read the research' links

- [x] We need to remove a couple of pieces of research that are currently unpublished (pieterse and de Lanerolle). Paola and I will do that.
